# Generated by Django 3.2.8 on 2021-10-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='fio',
            field=models.CharField(max_length=128, verbose_name='ФИО'),
        ),
    ]
